name: Pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run pytest
        run: |
          pytest
